### ISSUE TITLE
Update pre-built image

### ISSUE THREAD

**Issue by dalg24** [ORNL-CEES/Cap#141]
The goal of this issue is to put together a wish list for the next `cap-stack`. Please feel free to edit.
- ubuntu:16.04 as base image
- use package manager to install mpi/python
- install cppcheck
- upgrade trilinos to 12.6.3
- upgrade boost to 1.61.0

**Comment by dalg24** [comment]
- Enable Matplotlib animation (`apt-get install -y libav-tools`)
- Upgrade Boost to 1.62.0
- Upgrade Trilinos to 12.6.4 (or 12.8.1?)
- Upgrade deal.II to 8.4.2
- Pep8 replaced by pycodestyle
- Add symlink in `/usr/local/bin` to help CMake detect the appropriate Python interpreter.

**Comment by Rombur** [comment]
- Upgrade Boost to 1.63.0 (There is a problem with python in boost 1.64.0)
- Upgrade deal.II to 8.5.0
