### ISSUE TITLE
Error catch within ragone_plot.py

### ISSUE THREAD

**Issue by iSchomer** [ORNL-CEES/Cap#203]
``` python
def run_discharge(device, ptree):
    data = initialize_data()

    # (re)charge the device
    initial_voltage = ptree.get_double('initial_voltage')
```

When the `RagoneAnalysis` object calls `run_discharge`, that method tries to get two values from `PropertyTree`. 

``` python
except RuntimeError:
      print('Failed to discharge at {0} watt'.format(
                discharge_power))
      break
```

`RagoneAnalysis` catches that potential RuntimeError, but only with the assumption that it was caused by a failed constant-power discharge, so the user is not notified that they are missing `PropertyTree` entries.

**Comment by Rombur** [comment]
@iSchomer can you add the line and the file where we catch the exception

**Comment by dalg24** [comment]
Mm I see. The error log should indicate that the exception is thrown in the tree though. Is that not happening?

**Comment by Rombur** [comment]
Even if it does, it's pretty confusing to see an error message about a failed discharge when in fact the problem is a missing input.

**Comment by iSchomer** [comment]
Also it's worth mentioning that the automatic charge that happens within `run_discharge` is quite time-consuming with Dualfoil. The voltage hold at the end of the charge could last up to 40 minutes in run time I would guess.

**Comment by dalg24** [comment]
Yes we need to expose some of the parameters on the (re)charging step to the user.

**Comment by dalg24** [comment]
This isa possible fix

``` python
except RuntimeError as e:
    print(e)
    print('Failed to discharge at {0} watt'.format(discharge_power))
    break
```

**Comment by dalg24** [comment]
It is not ideal but I'm not sure we can throw different kind of errors with Boost.Python
See the [doc](http://www.boost.org/doc/libs/1_61_0/libs/python/doc/html/reference/high_level_components/boost_python_exception_translato.html)

**Comment by dalg24** [comment]
PR #205 should resolve this issue.
Errors raised from the `PropertyTree` will not be casted as `RuntimeError` any more.
