### ISSUE TITLE
suppress warnings

### ISSUE THREAD

**Issue by Rombur** [ORNL-CEES/Cap#244]
Now that jenkins shows the warnings we may want to clean up the code to suppress these warnings.

**Comment by dalg24** [comment]
For reference [Jenkins build#138](https://jupyterdocker.ornl.gov:8080/job/Cap-experimental/64/warnings28Result/NORMAL/).

- [ ] geometry.templates.h
- [x] mp_values.templates.h

I'll take care of `mp_values`, would you clean up `geometry`?
