### ISSUE TITLE
Refactor input for geometry

### ISSUE THREAD

**Issue by dalg24** [ORNL-CEES/Cap#38]
- [x] set `geometric_area` rather than `sandwich_height` and `sandwich_depth`
- [x] use word `thickness` rather than `width`
- [x] values given in units of cm

**Comment by Rombur** [comment]
I just made this a little bit nicer so now you can click on it and have a nice progression bar :-D

**Comment by dalg24** [comment]
nice

**Comment by dalg24** [comment]
how do you do that?

**Comment by dalg24** [comment]
note that involve adjustments to `compute_equivalent_circuit`

**Comment by dalg24** [comment]
PR #43 resolves the issue
