### ISSUE TITLE
cpp tests spring cleaning

### ISSUE THREAD

**Issue by dalg24** [ORNL-CEES/Cap#52]
- [x] **butler_volmer_kinetics**
  - only checks that F/RT==1/k_bT and plots linearized kinetics vs exponential form
  - integrate into material properties test or remove
- [x] **charge_curve**
- [x] **discharge_curve**
- [x] **cyclic_voltammetry**
- [x] **leakage_current** (measures both direct leakage current and self discharge)
- [x] **lissajous_curve**
- [x] **impedance_spectroscopy** (requires GSL)
  - these are not checking anything, they are more examples
- [x] **impedance_spectroscopy-2** (checks analytical solution for equivalent circuits)
- [x] **ragone_chart**
  - not checking anything, just a driver to measure the device performance
- [x] **ragone_chart-2**
  - checks against analytical solution for series and parallel rc circuits
- [x] **discrete_fourier_transform** (compares GSL fft with NumPy)
- [x] **resistor_capacitor_circuit** (tests series and parallel rc circuits)
- [x] **resistor_capacitor_circuit-2**
  - measures impedance spectra but doesn't assert anything
  - compares step versus ramp
- [x] **geometry**
- [x] **mp_values**
- [x] **postprocessor** (checks approximation of integral with trapezoidal rule and compute power/energy)
  - move into deal.II directory
- [x] **dirichlet_boundary_operator**
  - boundary op is not used...
- [x]  **uq** (uses TASMANIAN)
- [x] **exact_transient_solution**
- [x] **exact_transient_solution-2**
- [x] **equivalent_circuit-2** (computes equiv circuit to a supercap and plots CCD)
  - we need to revisit this test
- [x] **energy_storage_device**
- [x] **supercapacitor**
- [x] **parse_params**
  - multiple checks all related to property trees
- [x] **multi_stage**

**Comment by dalg24** [comment]
PR #56 removed butler_volmer_kinetics, charge_curve, discharge_curve, and cyclic_voltammetry

**Comment by dalg24** [comment]
PR #58 removed lissajous_curve, leakage_current, ragone_chart-2, and impedance_spectroscopy-2

impedance_spectroscopy and ragone_chart are checking results with equivalent circuits
their input was converted to .info format

**Comment by dalg24** [comment]
PR #60 reviewed discrete_fourier_transform, resistor_capacitor_circuit, resistor_capacitor_circuit-2, geometry, and mp_values

Note that:
- resistor_capacitor-2 will be soon removed.
- resistor_capacitor needs testing for linear evolution.
- impedance_spectroscopy and argon_chart are testing either SeriesRC or ParallelRC but **not** both. this will need to be addressed.

**Comment by dalg24** [comment]
PR #65 removed uq, dirichlet_boundary_operator, and multistage.
postprocessor is updated, now using Boost.Odeint rather than trapezoidal rule.

**Comment by dalg24** [comment]
PR #72 cleaned equivalent_circuit.

**Comment by Rombur** [comment]
PR #82 cleaned exact_transient_solution.

**Comment by dalg24** [comment]
PR #89 simply removed `exact_transient_solution-2`

**Comment by dalg24** [comment]
@Rombur Are we good to close the issue then?

**Comment by Rombur** [comment]
Yes, I will open a new one for the new tests to add.
