### ISSUE TITLE
Dead kernel while running notebook

### ISSUE THREAD

**Issue by dalg24** [ORNL-CEES/Cap#85]
Got the error `dead kernel` while running EIS measurement.
After investigation turned out the solver was not able to converge.
Material properties and geometry departed from nominal values that were previously used.
The "default" solver settings need adjustments.

**Comment by Rombur** [comment]
I thought that you were the convergence expert ;-)

**Comment by dalg24** [comment]
just relax the convergence criterion, it never fails...

**Comment by Rombur** [comment]
It was a problem in the input files. The position of the electrochemical block was different in the input file and in the code.
