### ISSUE TITLE
Headers in EC-Lab output

### ISSUE THREAD

**Issue by dalg24** [ORNL-CEES/Cap#86]
This is a feature request by Frank.
- [x] Compute total interfacial area in the electrode
- [x] Print it in the EC-Lab file
- [x] Print some of the input parameters as well
- [x] Also put git commit hash somewhere

**Comment by dalg24** [comment]
@Rombur Would you remind me what input need to be written?

**Comment by Rombur** [comment]
Yeah I'll add it tomorrow.

**Comment by dalg24** [comment]
An idea:
we copy any line that ends with `;x`
it means no need to iterate if he decides he wants to save some other input

**Comment by Rombur** [comment]
Here are the output that he wants:
- geometric area of electrode [cm^2]
- thickness of electrode [cm]
- porosity (void volume fraction)
- double layer capacitance [microFarad/cm^2]
- total surface area in electrode [m^2] or [cm^2]
- mass of active material in electrode [g]

**Comment by dalg24** [comment]
Need final adjustments.

**Comment by dalg24** [comment]
Waiting to hear back from Frank before closing this

**Comment by dalg24** [comment]
We had encoding issues to deal with. PR #92 fix it.

**Comment by dalg24** [comment]
Units were wrong. PR #94 fixed it.
