### ISSUE TITLE
Failing unit tests in the CTest script won't make travis report fail!

### ISSUE THREAD

**Issue by dalg24** [ORNL-CEES/Cap#88]
See https://travis-ci.org/ORNL-CEES/Cap/builds/120219526 for illustration.

```
The following tests FAILED:
     15 - test_energy_storage_device_wrappers_py (Failed)
```

but the status on TravisCI is `#289 passed`

**Comment by Rombur** [comment]
How to use clang/gcc for memory check: http://clang.llvm.org/docs/AddressSanitizer.html

**Comment by dalg24** [comment]
Issue is resolved
